package com.example.lamur.exchangesstudents;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import com.google.gson.Gson;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Admin_page extends AppCompatActivity {

    ListView list;
    DBHelper dbhelper = DBHelper.getInstance(this);
    ServiceCustomAdapter myCustomAdapter;

    Services _services_selected = new Services();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_admin_page);

        list = (ListView) findViewById(R.id.list_user);


        ArrayList<Services> ls = dbhelper.listService();
        myCustomAdapter = new ServiceCustomAdapter(Admin_page.this, ls);

        list.setAdapter(myCustomAdapter);

        myCustomAdapter.updateReceiptsList(ls);

        list.setOnItemClickListener(new AdapterView.OnItemClickListener(){

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position,
                                    long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.

                Services serv = (Services) myCustomAdapter.getItem(position);

                _services_selected = serv;

                }


        });



    }

    @Override
    protected void onResume() {
        super.onResume();
        ArrayList<Services> ls = dbhelper.listService();
        myCustomAdapter.updateReceiptsList(ls);
    }

    public void listProprio(View view)
    {
        ArrayList<User> _lprio = dbhelper.listProprio();
        if(_lprio.size() == 0)
        {
            Toast.makeText(this, "pas de propriétaire détecté", Toast.LENGTH_LONG).show();
        }
        else {
            Intent intent = new Intent(this, Liste_user.class);
            intent.putExtra("LIST_OF_OBJECTS", _lprio);
            intent.putExtra("ROLE_ID", "Proprietaire");
            startActivity(intent);
        }
    }

    public void listFournisseur(View view)
    {
        ArrayList<User> _lfour = dbhelper.listFournisseur();
        if(_lfour.size() == 0)
        {
            Toast.makeText(this, "pas de fournissuer détecté", Toast.LENGTH_LONG).show();
        }
        else {
            Intent intent = new Intent(this, Liste_user.class);

            intent.putExtra("LIST_OF_OBJECTS", _lfour);
            intent.putExtra("ROLE_ID", "Fournisseur");
            startActivity(intent);
        }
    }

    public void Ajout_Service(View view)
    {
        Intent intent = new Intent(this, Ajout_service.class);

        startActivity(intent);


        ArrayList<Services> ls = dbhelper.listService();
        myCustomAdapter.updateReceiptsList(ls);

    }

    public void modifier_Service(View view){

        Intent intent = new Intent(Admin_page.this, Modifier_service.class);
        intent.putExtra("Service", _services_selected);

        startActivity(intent);

    }

    public void Ajout_Categorie(View view)
    {
        Intent intent = new Intent(this, Ajout_service.class);

        startActivity(intent);
    }


}
