package com.example.lamur.exchangesstudents;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

public class Sign_in_utilisateur extends AppCompatActivity {


    String nom,role;
    TextView name;
    User user;
    ListView list;
    DBHelper dbhelper = DBHelper.getInstance(this);
    ArrayList<Service_Disponibilite> listOfValues = new ArrayList<>();
    DisponibiliteAdaptater myCustomAdapter;
    Service_Disponibilite _serv_selected = new Service_Disponibilite();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_welcome_page_utilisateur);
        Intent intent = getIntent();
        Bundle extras = intent.getExtras();


        name = (TextView) findViewById(R.id.nom_user);
        name.setText(user.get_username());

        HashMap<Integer,Service_Disponibilite> Listhash = new HashMap<>();
        Listhash = dbhelper.ServicesByFournisseur(user.get_id());



        if(Listhash.isEmpty()) {

            listOfValues = new ArrayList<>();


            myCustomAdapter = new DisponibiliteAdaptater(Sign_in_utilisateur.this, listOfValues);

            list.setAdapter(myCustomAdapter);

            myCustomAdapter.updateReceiptsList(listOfValues);

            list.setOnItemClickListener(new AdapterView.OnItemClickListener(){



                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position,
                                        long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.

                    Service_Disponibilite serv = (Service_Disponibilite) myCustomAdapter.getItem(position);

                    _serv_selected = serv;

                }


            });

        }
        else
        {

            Collection<Service_Disponibilite> values = Listhash.values();

            //Creating an ArrayList of values

            listOfValues = new ArrayList<>(values);


            myCustomAdapter = new DisponibiliteAdaptater(Sign_in_utilisateur.this, listOfValues);

            list.setAdapter(myCustomAdapter);

            myCustomAdapter.updateReceiptsList(listOfValues);

            list.setOnItemClickListener(new AdapterView.OnItemClickListener(){

                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position,
                                        long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.

                    Service_Disponibilite serv = (Service_Disponibilite) myCustomAdapter.getItem(position);

                    _serv_selected = serv;

                }


            });

        }




    }

    public void ajouter_Service(View view){


    }
}
