package com.example.lamur.exchangesstudents;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;

public class Sign_in_utilisateur extends AppCompatActivity {


    String nom,role;
    TextView name;
    Proprietaire user;
    ListView list;
    ArrayAdapter<String> adapter;
    DBHelper dbhelper = DBHelper.getInstance(this);
    ArrayList<Rendez_Vous> listOfValues = new ArrayList<>();
    RdvCustomAdapter myCustomAdapter;
    Rendez_Vous rdv;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_welcome_page_utilisateur);
        Intent intent = getIntent();
        Bundle extras = intent.getExtras();

        role = extras.getString("role");
        if(role.equals("Propriétaire")) {
            user = (Proprietaire) this.getIntent().getSerializableExtra("info_user");
        }
        name = (TextView) findViewById(R.id.nom_user);
        name.setText(user.get_username());

        list = (ListView) findViewById(R.id.Liste_activite);



        HashMap<Integer,Rendez_Vous> Listhash = new HashMap<>();
        Listhash = dbhelper.ServicesByUser(user.get_id());

        if(Listhash.isEmpty())
        {
            listOfValues = new ArrayList<>();


            myCustomAdapter = new RdvCustomAdapter(Sign_in_utilisateur.this, listOfValues);

            list.setAdapter(myCustomAdapter);

        }
        else {

            Collection<Rendez_Vous> values = Listhash.values();

            listOfValues = new ArrayList<>(values);

            list = (ListView) findViewById(R.id.liste_service);

                       myCustomAdapter = new RdvCustomAdapter(Sign_in_utilisateur.this, listOfValues);

            list.setAdapter(myCustomAdapter);

            myCustomAdapter.updateReceiptsList(listOfValues);

        }

        list.setOnItemClickListener(new AdapterView.OnItemClickListener(){

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position,
                                    long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.

                Rendez_Vous serv = (Rendez_Vous) myCustomAdapter.getItem(position);

                rdv = serv;

            }


        });




    }


    @Override
    protected void onResume() {
        super.onResume();
        HashMap<Integer,Rendez_Vous>  Listhash = new HashMap<>();
        Listhash = dbhelper.ServicesByUser(user.get_id());

        if(Listhash.isEmpty()) {


            //Creating an ArrayList of values

            ArrayList<Rendez_Vous> _new_list = new ArrayList<Rendez_Vous>();

            myCustomAdapter.updateReceiptsList(_new_list);
        }
        else
        {


            Collection<Rendez_Vous> values = Listhash.values();

            //Creating an ArrayList of values

            ArrayList<Rendez_Vous> _new_list = new ArrayList<>(values);

            myCustomAdapter.updateReceiptsList(_new_list);

        }
    }


    public void ajouter_Service(View view){


        Intent add_service = new Intent(this, Search_Disponibilite.class);
        Bundle extras = new Bundle();

        extras.putSerializable("info_user",user);
        add_service.putExtras(extras);
        startActivity(add_service);

    }

    public void Note_Commente(View view)
    {
        Intent add_service = new Intent(this, NoteRdv.class);
        Bundle extras = new Bundle();
        extras.putSerializable("info_user",user);
        extras.putSerializable("info_rdv",rdv);
        add_service.putExtras(extras);
    }
}
